describe('Actions', () => {
  it('reaches website', () => {
    cy.visit('http://127.0.0.1:5000/')
  })
  it('lets you log in', () => {
    cy.visit('http://127.0.0.1:5000/')
      .get('[name=login]').click()
      .get('#username').type('seashellsmith')
      .get('#password').type('Testing')
      .get('button').click()
    cy.contains('Word Counter App')
  })
  it('fails with wrong password', () => {
    cy.visit('http://127.0.0.1:5000/')
      .get('[name=login]').click()
      .get('#username').type('seashellsmith')
      .get('#password').type('lizzie!!!!')
      .get('button').click()
    cy.contains('Please Log In')
  })
  it('lets you register', () => {
    const username = 'user' + Math.floor(Math.random() * 10000000);
    const password = 'pass' + Math.floor(Math.random() * 10000000);
    cy.visit('http://127.0.0.1:5000/')
      .get('[name=register]').click()
      .get('#username').type(username)
      .get('#password1').type(password)
      .get('#password2').type(password)
      .get('button').click()
    cy.contains('Please Log In')
      .get('#username').type(username)
      .get('#password').type(password)
      .get('button').click()
    cy.contains('Word Counter App')
  })
  it('fails to register if username exists', () => {
    const password = 'pass' + Math.floor(Math.random() * 10000000);
    cy.visit('http://127.0.0.1:5000/')
      .get('[name=register]').click()
      .get('#username').type('seashellsmith')
      .get('#password1').type(password)
      .get('#password2').type(password)
      .get('button').click()
    cy.contains('Enter your information')
  })
  it('fails to register if passwords do not match', () => {
    const username = 'user' + Math.floor(Math.random() * 10000000);
    const password = 'pass' + Math.floor(Math.random() * 10000000);
    const password2 = 'pass' + Math.floor(Math.random() * 10000000);
    cy.visit('http://127.0.0.1:5000/')
      .get('[name=register]').click()
      .get('#username').type(username)
      .get('#password1').type(password)
      .get('#password2').type(password2)
      .get('button').click()
    cy.contains('Enter your information')
  })
  it('Loads correct word count after logging in', () => {
    cy.visit('http://127.0.0.1:5000/')
    .get('[name=login]').click()
    .get('#username').type('Tester2')
    .get('#password').type('Tester')
    .get('button').click()
  cy.contains('Lifetime word count: 5')
  })
  it('counts words correctly', () => {
    cy.visit('http://127.0.0.1:5000/')
    .get('[name=login]').click()
    .get('#username').type('Tester3')
    .get('#password').type('Tester')
    .get('button').click()
  cy.contains('New words: 0')
    .get('#content').type('Mary had a little lamb')
    .get('[name=submit]').click()
  cy.contains('New words: 5')
    .get('#content').type('Mary\n')
    .get('#content').type('had\n')
    .get('#content').type('a\n')
    .get('#content').type('little\n')
    .get('#content').type('lamb\n')
    .get('[name=submit]').click()
  cy.contains('New words: 5')
    .get('#content').type('Mary-anne, "had" a, little. lamb!')
    .get('[name=submit]').click()
  cy.contains('New words: 5')
  })
})